export const ROUTES = {
  home: "/",
  login: "/login",
  profile: "/profile",
  learn: "/learn",
  learnCourses: "/learn?tab=courses",
  learnPaths: "/learn?tab=paths",
  coding: "/coding-os?tab=practice",
  codingEditor: "/coding-os?tab=practice",
  codingSubmissions: "/coding-os?tab=history",
  dsa: "/coding-os?tab=dsa",
  dsaPractice: "/coding-os?tab=practice",
  dsaRoadmap: "/coding-os?tab=dsa",
  assessments: "/assessments",
  assessmentsTake: "/assessments?tab=take",
  assessmentsBank: "/assessments?tab=bank",
  resume: "/career-os?tab=resume",
  resumeBuilder: "/career-os?tab=resume",
  resumeList: "/career-os?tab=resume",
  ats: "/career-os?tab=ats",
  atsAnalyze: "/career-os?tab=ats",
  atsReport: "/career-os?tab=ats",
  resumeAnalysis: "/resume-analysis",
  interview: "/interview",
  interviewStart: "/interview?tab=mock",
  interviewSession: "/interview/session",
  interviewVoice: "/interview/voice",
  interviewPanel: "/interview/panel",
  interviewCoding: "/interview/coding",
  interviewReport: "/interview/report",
  interviewHistory: "/interview?tab=history",
  apiHealth: "/api/health",
  apiAgents: "/api/agents",
  apiPlacementReadiness: "/api/placement/readiness",
  twin: "/career-os?tab=twin",
  twinDashboard: "/career-os?tab=twin",
  professionalIntelligence: "/dashboard/professional-intelligence",
  portfolio: "/portfolio",
  portfolioBuilder: "/portfolio?tab=builder",
  portfolioShare: "/portfolio?tab=share",
  projects: "/projects",
  projectsNew: "/projects?tab=new",
  projectsExplore: "/projects?tab=explore",
  placements: "/placements",
  placementsDrives: "/placements?tab=drives",
  placementsApplications: "/placements?tab=applications",
  aiCoach: "/ai-coach",
  aiRecommendations: "/ai-coach?tab=recommendations",
  aiSkillGap: "/ai-coach?tab=skill-gap",
  analytics: "/analytics",
  leaderboard: "/leaderboard",
  leaderboardRankings: "/leaderboard?tab=rankings",
  leaderboardAchievements: "/leaderboard?tab=achievements",
  office: "/office",
  careerOs: "/career-os",
  codingOs: "/coding-os",
} as const;

export const SEARCH_ROUTES = [
  { keywords: ["learn", "course", "lms", "video"], href: ROUTES.careerOs },
  { keywords: ["code", "compiler", "lab", "python", "java", "leetcode", "hackerrank"], href: ROUTES.codingOs },
  { keywords: ["dsa", "algorithm", "array", "tree", "graph"], href: ROUTES.codingOs },
  { keywords: ["assessment", "exam", "quiz", "test", "mcq"], href: ROUTES.interview },
  { keywords: ["resume", "cv"], href: ROUTES.resume },
  { keywords: ["ats", "scan", "keyword"], href: ROUTES.ats },
  { keywords: ["interview", "mock", "hr"], href: ROUTES.interview },
  { keywords: ["office", "workplace", "standup", "sprint"], href: ROUTES.office },
  { keywords: ["portfolio", "profile video"], href: ROUTES.resume },
  { keywords: ["project", "github"], href: ROUTES.projects },
  { keywords: ["placement", "drive", "company", "job"], href: ROUTES.careerOs },
  { keywords: ["ai", "coach", "career", "recommend"], href: ROUTES.careerOs },
  { keywords: ["analytics", "report", "chart"], href: ROUTES.analytics },
  { keywords: ["leaderboard", "rank", "badge", "xp"], href: ROUTES.leaderboard },
  { keywords: ["profile", "settings", "account"], href: ROUTES.profile },
];
