export const ROUTES = {
  home: "/",
  login: "/login",
  profile: "/profile",
  learn: "/learn",
  learnCourses: "/learn?tab=courses",
  learnPaths: "/learn?tab=paths",
  coding: "/coding",
  codingEditor: "/coding?tab=editor",
  codingSubmissions: "/coding?tab=submissions",
  dsa: "/dsa",
  dsaPractice: "/dsa?tab=practice",
  dsaRoadmap: "/dsa?tab=roadmap",
  assessments: "/assessments",
  assessmentsTake: "/assessments?tab=take",
  assessmentsBank: "/assessments?tab=bank",
  resume: "/resume",
  resumeBuilder: "/resume?tab=builder",
  resumeList: "/resume?tab=list",
  ats: "/ats",
  atsAnalyze: "/ats?tab=analyze",
  atsReport: "/ats?tab=report",
  resumeAnalysis: "/resume-analysis",
  interview: "/interview",
  interviewStart: "/interview?tab=start",
  interviewSession: "/interview/session",
  interviewVoice: "/interview/voice",
  interviewPanel: "/interview/panel",
  interviewCoding: "/interview/coding",
  interviewReport: "/interview/report",
  interviewHistory: "/interview?tab=history",
  apiHealth: "/api/health",
  apiAgents: "/api/agents",
  apiPlacementReadiness: "/api/placement/readiness",
  twin: "/twin",
  twinDashboard: "/twin?tab=overview",
  professionalIntelligence: "/dashboard/professional-intelligence",
  portfolio: "/portfolio",
  portfolioBuilder: "/portfolio?tab=builder",
  portfolioShare: "/portfolio?tab=share",
  projects: "/projects",
  projectsNew: "/projects?tab=new",
  projectsExplore: "/projects?tab=explore",
  placements: "/placements",
  placementsDrives: "/placements?tab=drives",
  placementsApplications: "/placements?tab=applications",
  aiCoach: "/ai-coach",
  aiRecommendations: "/ai-coach?tab=recommendations",
  aiSkillGap: "/ai-coach?tab=skill-gap",
  analytics: "/analytics",
  leaderboard: "/leaderboard",
  leaderboardRankings: "/leaderboard?tab=rankings",
  leaderboardAchievements: "/leaderboard?tab=achievements",
} as const;

export const SEARCH_ROUTES = [
  { keywords: ["learn", "course", "lms", "video"], href: ROUTES.learn },
  { keywords: ["code", "compiler", "lab", "python", "java"], href: ROUTES.coding },
  { keywords: ["dsa", "algorithm", "array", "tree", "graph"], href: ROUTES.dsa },
  { keywords: ["assessment", "exam", "quiz", "test", "mcq"], href: ROUTES.assessments },
  { keywords: ["resume", "cv"], href: ROUTES.resume },
  { keywords: ["ats", "scan", "keyword"], href: ROUTES.ats },
  { keywords: ["interview", "mock", "hr"], href: ROUTES.interview },
  { keywords: ["portfolio", "profile video"], href: ROUTES.portfolio },
  { keywords: ["project", "github"], href: ROUTES.projects },
  { keywords: ["placement", "drive", "company", "job"], href: ROUTES.placements },
  { keywords: ["ai", "coach", "career", "recommend"], href: ROUTES.aiCoach },
  { keywords: ["analytics", "report", "chart"], href: ROUTES.analytics },
  { keywords: ["leaderboard", "rank", "badge", "xp"], href: ROUTES.leaderboard },
  { keywords: ["profile", "settings", "account"], href: ROUTES.profile },
];
